### PR TITLE
Add note about older Intel gen4-7 graphics and Crocus

### PR DESCRIPTION
**Pull request by ValdikSS**

### CODE REVIEW

**Comment by ValdikSS** [comment]
Is it possible for Gallium Nine to automatically force Crocus if i965 is detected?

**Comment by axeldavy** [comment]
I'm not sure Gallium nine can be used on all these graphic cards. Indeed we require the cards to be able to support the full dx9 feature set (vs/ps 3). I think the oldest ones will fail when launching with gallium nine (there is a capability check)?

**Comment by ValdikSS** [comment]
Gen 4 cards support full DX9 I believe (9.0c FL9_1 according to [Wikipedia](https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Gen4)). This is the earliest card which crocus supports. Is this feature set sufficient?

**Comment by axeldavy** [comment]
GMA 3000 says "3.0 (SW) / 2.0". That is insufficient. Maybe GMA X3000 would be ok.

**Comment by ValdikSS** [comment]
Just to clarify, i965 is not a gallium driver, so gallium-nine could not be used with i965 at all.

**Comment by axeldavy** [comment]
@dhewg What do you think ?

**Comment by dhewg** [comment]
Sure, why not.
This could even be expanded to list all possible nine-capable drivers.

**Comment by lorn10** [comment]
Here follows a short addition out of an "user perspective". I think it would be in this context really useful to add explicitly also the "**Shader model 3.0**" or "**feature level 9_3**" requirement. So the people must realize that Gallium Nine works only with DirectX 9.0**c** compliant hardware, not with 9.0b or 9.0a.

A nice source can be found here: https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Gen4

This would result then in a slightly more detailed text:
```
Intel Drivers
-------------
Gallium Nine could be used with the new Crocus driver (included since Mesa 21.2) on older Shader model 3.0 aka feature level 9_3 compatible Intel gen4-7 graphics (GMA X3000, GMA 4500, HD 2000-5000; year 2007-2014).

Use the environment variable ``MESA_LOADER_DRIVER_OVERRIDE=crocus`` to force using Crocus instead of i965.

All newer Intel iGPU hardware is supported through the already working Iris driver.
```

**Comment by ValdikSS** [comment]
Done.

**Comment by ValdikSS** [comment]
Any other suggestions, changes?

**Comment by dhewg** [comment]
Only nitpicks, but I guess that's enough procrastination ;)
Thanks and sorry for the delay!

**Pull request merged**
