### PR TITLE
bootstrap: add nixos support

### PR DESCRIPTION
**Pull request by 9ary**
I'm packaging this project for NixOS.

https://github.com/NixOS/nixpkgs/pull/220853

### CODE REVIEW

**Comment by dhewg** [comment]
There really is no /etc/os-release? That sounds... fishy?

**Comment by 9ary** [comment]
It exists at runtime, but isn't present in the build environment. This is probably related to purity.

**Comment by dhewg** [comment]
Okay, I don't know nixos, but np, we can merge this.
But the next question is: there really is no arch specific pkg-config?

**Comment by 9ary** [comment]
Indeed, the way multilib works on nixos is different from most other distros. Each package is installed to a dedicated prefix in the nix store, with a hash in the path. This allows multiple versions and builds of the same package to coexist, so the 32 bit packages are just those from the 32 bit distribution. At build time, packages for only one architecture will be available so there is no need to discriminate between the 32 bit and 64 bit pkg-config.

**Comment by dhewg** [comment]
Alright, thanks for the patches!

**Pull request merged**
